### ISSUE TITLE
Call milo opc-ua server ConditionType_ConditionRefresh method failed.

### ISSUE THREAD

**Issue by cityWalker312** [eclipse/milo#1073] opened 2022-10-27 09:27 UTC
**Describe the bug**
Use milo client call milo opc-ua server ConditionType_ConditionRefresh failed.
We try to call the method from UaExpert app failed too on milo opc-ua server.

Use milo client call open62541 opc-ua server ConditionType_ConditionRefresh successfully.

Here is the call method codeblock.
```java
private boolean callConditionRefresh(OpcUaClient client, CompletableFuture<OpcUaClient> future, int subId) {
        NodeId objectId = Identifiers.ConditionType;
        NodeId methodId = Identifiers.ConditionType_ConditionRefresh;
        CallMethodRequest request = new CallMethodRequest(
                objectId,
                methodId,
                new Variant[]{new Variant(UInteger.valueOf(subId))}
        );
        client.call(request).thenCompose(result -> {
            StatusCode statusCode = result.getStatusCode();
            if (statusCode.isGood()) {
                return CompletableFuture.completedFuture(0);
            } else {
                StatusCode[] inputArgumentResults = result.getInputArgumentResults();
                if (inputArgumentResults != null) {
                    for (int i = 0; i < inputArgumentResults.length; i++) {
                        logger.error("inputArgumentResults[{}]={}", i, inputArgumentResults[i]);
                    }
                }
                CompletableFuture<Integer> f = new CompletableFuture<>();
                f.completeExceptionally(new UaException(statusCode));
                return f;
            }
        });

        return true;
    }
```

**Expected behavior**
Call the ConditionType_ConditionRefresh method successfull.

**Logs and Packet Captures**
If applicable, add application logs or Wireshark captures to help explain your problem.
![image](https://user-images.githubusercontent.com/17649507/198247387-42d66b28-42cb-4e7d-81b7-311fdc837c67.png)

**Additional context**
The milo version is 0.6.3.

**Comment by kevinherron** [comment] 2022-10-28 14:55
Thanks for the report, this does look like a bug in the Milo server. 

Note to future self: the issue is "known" and will be fixed when this TODO is resolved:
https://github.com/eclipse/milo/blob/3419235853491ac89f3391bffd337c8200522522/opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/methods/AbstractMethodInvocationHandler.java#L79-L83

**Comment by cityWalker312** [comment] 2022-10-29 03:47
> Thanks for the report, this does look like a bug in the Milo server.
> 
> Note to future self: the issue is "known" and will be fixed when this TODO is resolved:
> 
> https://github.com/eclipse/milo/blob/3419235853491ac89f3391bffd337c8200522522/opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/methods/AbstractMethodInvocationHandler.java#L79-L83

Thanks for your reply. 
Does milo have a plan to fix this issue ? Our  project need to use this feature.

**Comment by kevinherron** [comment] 2024-03-16 21:11
WIP branch with a test that reproduces: https://github.com/eclipse/milo/tree/issues/gh1073

**Comment by kevinherron** [comment] 2024-03-17 14:30
Fixed in https://github.com/eclipse/milo/commit/73e9fef7b933198471ad25e747c845044d3d5880 for 1.0 release.

**Closed by kevinherron** 2024-03-17 14:30 UTC
