### ISSUE TITLE
Uncaught Exception when OPC UA connection terminates unexpectedly

### ISSUE THREAD

**Issue by danyadibence** [eclipse/milo#332] opened 2018-10-08 12:59 UTC
Hi,

I would like to test what happens if the OPC UA client (developed using Eclipse Milo) loses connection to a server (ProSys OPC UA Simulation Server), because the server is not available any more. I tested the connection's termination by closing the simulation server.
However, in this case the following exception will be thrown and logged regularly:
```
2018-10-08 14:45:12.029  WARN 19244 --- [ty-event-loop-6] i.n.c.DefaultChannelPipeline             : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382) ~[?:?]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

Is there a way to handle this exception so that it won't appear in the logs all the time? It might cause the log files to contain unnecessary informations about the lost connection.

Thank you very much in advance!

**Comment by danyadibence** [comment] 2018-10-08 14:30
Yes, it would translate to something similar. According to [this](https://github.com/netty/netty/issues/4897) issue the precise description is "An established connection was aborted by the software in your host machine"

**Comment by kevinherron** [comment] 2018-10-08 16:45
What version of Milo are you using? I'm not able to reproduce this.

**Comment by danyadibence** [comment] 2018-10-09 08:01
I'm using 0.2.3.
I forgot to add in my previous comments that I have variable subscriptions, sorry for that.

**Comment by kevinherron** [comment] 2018-10-09 14:12
I still can't reproduce this.

The Exception you're getting is suspicious - it's one I'd expect to see if e.g. the network adapter was disabled or your IP address changed or something, not one you should see from just closing the simulation server. Can you tell me more about how you're testing this? OS? Client and server on same machine?

I think this is just a matter of override `exceptionCaught` in one of the handlers (maybe `UaTcpClientAcknoledgeHandler`, but I can't be sure without reproducing it. If you're in a position to make some changes and recompile them yourself that would help too.

**Comment by danyadibence** [comment] 2018-10-09 14:29
Thank you for your help. The server and client are on the same Windows 10 machine.

I'll try overriding an exceptionCaught() method.

**Comment by danyadibence** [comment] 2018-10-10 10:14
Hi @kevinherron,

I managed to solve the problem, it was caused by a thread used for a different use-case.
I reorganised my threads and their synchronization and now the redundant log messages aren't visible any more.

**Comment by kevinherron** [comment] 2018-10-10 11:57
Ok, great :+1:

**Closed by kevinherron** 2018-10-10 11:57 UTC

**Comment by Po252** [comment] 2022-03-24 03:21
> Hi @kevinherron,
> 
> I managed to solve the problem, it was caused by a thread used for a different use-case. I reorganised my threads and their synchronization and now the redundant log messages aren't visible any more.
Hi @danyadibence 
help😂,my milo version is 0.2.4 .But I don't know this threads should be reorganized

**Comment by tsmortenson** [comment] 2025-01-21 10:25
We also still see this regularly while shutting down out application with version 0.6.15

```
ERROR  *[k.client.transport.uasc.UascClientMessageHandler] (milo-netty-event-loop-5                                              ): [remote=kwi-lacs-y7-1/10.210.1.10:52240] Exception caught: 既存の接続はリモート ホストに強制的に切断されました。
java.io.IOException: 既存の接続はリモート ホストに強制的に切断されました。
      at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
      at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
      at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
      at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
      at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
      at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
      at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[netty-buffer-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:356) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994) ~[netty-common-4.1.112.Final.jar:4.1.112.Final]
      at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.112.Final.jar:4.1.112.Final]
      at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

We ended up adding a lot of allocate/release code to make sure the OpcUaClient and its NodeManager are never disposed while they are still in use.   Then also made sure toe delete any subscriptions that had been made.
What finally fixed the problem though was to change the code:
```
opcUaClient.disconnect();
opcUaClient = null;
```
to:
```
opcUaClient.disconnect().get();
opcUaClient = null;
```
This seems to make sure the code waits for the disconnect to actually complete before proceeding to dispose the OpcUaClient instance during shutdown of the JVM.

Hope this helps.
